""" GPS map-matching functions.

 Created 2013-07-11. Based on previous work by Jacob Blair for Lane Council of
 Governments.

 Licensed under The MIT License (MIT).
 http://opensource.org/licenses/MIT

 Copyright (c) 2013 Jacob Blair.


 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 """

 ##from mapmatch.gps import ##
 ##from mapmatch.matcher import ##
 ##from mapmatch.network import ##